require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'example/**/*'
Layout/LineLength:
  Max: 120
Lint/UriEscapeUnescape:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 18
  Exclude:
    - app/controllers/core/cli_options.rb
Metrics/PerceivedComplexity:
  Max: 9
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - lib/cms_scanner/finders/finder.rb
Style/MixinUsage:
  Exclude:
    - lib/cms_scanner/formatter.rb
